name: AWS SSM Send-Command Example

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    build:
          runs-on: ubuntu-latest
      
          steps:
          - uses: actions/checkout@v1
          - name: Install Node.js
            uses: actions/setup-node@v1
            with:
              node-version: '10.x'
          - name: Install npm dependencies
            run: yarn install
          - name: Run build task
            run: npm build
          - name: Deploy to Server
            uses: easingthemes/ssh-deploy@v2.1.1
            env:
                SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                SOURCE: "build/"
                REMOTE_HOST: ec2-18-163-50-26.ap-east-1.compute.amazonaws.com
                REMOTE_USER: ubuntu
                TARGET: /home/ubuntu/backend/test
